version: '3'

services:
  web:
    container_name: web_dev
    build:
      context: ../../
      dockerfile: ./docker/dev/dev.dockerfile
    volumes:
      - ../../.:/code
    ports:
      - "8080:8080"
    env_file:
      - ./env/django.dev.env
    depends_on:
      - db

  db:
    container_name: db_dev
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/db.dev.env

volumes:
  postgres_data:
