version: '3'

services:
  web:
    container_name: web
    build: .
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    env_file:
      - ./django.dev.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db.dev.env

volumes:
  postgres_data:
