version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: prod.dockerfile
    expose:
      - 8000
    env_file:
      - ./django.prod.env
      - ./gunicorn.prod.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db.prod.env

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
