version: '3'

services:
  web:
    container_name: web_prod
    build:
      context: ../../
      dockerfile: ./docker/prod/prod.dockerfile
    expose:
      - 8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    env_file:
      - ./env/django.prod.env
      - ./env/gunicorn.prod.env
    depends_on:
      - db

  db:
    container_name: db_prod
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/db.prod.env

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
